server:
  name: "project_api"
  addr: "127.0.0.1:8080"


zap:
  DebugFileName: "/Users/zuoliang/Documents/go_project/ms_project/logs/debug/project-debug.log"
  InfoFileName: "/Users/zuoliang/Documents/go_project/ms_project/logs/error/project-error.log"
  WarnFileName: "/Users/zuoliang/Documents/go_project/ms_project/logs/info/project-info.log"
  MaxSize: 500,
  MaxAge: 28,
  MaxBackups: 3,
etcd:
  addrs:
    - "127.0.0.1:2379"